### ISSUE TITLE
有交叉编译的方式吗

### ISSUE THREAD

**Issue by JustinWuCN** [cattyhouse/pkgbuild-linux-phicomm-n1#1]
在N1里编译这个内核,花费了很长的时间.
有没有办法可以在x86上编译完成了,安装到N1里?

----

http://kr1.us.to/kernel/ 这个网站访问不了.无法下载你编译好的内核.只能靠自己编译

**Comment by cattyhouse** [comment]
两个方向

1. distcc 配合 x86的机器. 
2. 如果你有 M1的苹果电脑, 虚拟一个archlinux. 直接编译, 10分钟一个内核到手. 
2.1. 如果你有 甲骨文的免费的 arm 的vps, 也可以将其系统替换成 arch linux arm. 然后直接编译. 4核心的大概 25分钟, 2核心的大概50分钟.

**Comment by cattyhouse** [comment]
我觉得内核不需要经常更新, 除非像前几天爆出重大的漏洞 (Dirty Pipe). 我这个内核基本上停留在 linux-lts 5.15.x

**Comment by cattyhouse** [comment]
交叉编译参考

https://github.com/cattyhouse/notes/blob/main/distcc.md

**Comment by JustinWuCN** [comment]
> 交叉编译参考
> 
> https://github.com/cattyhouse/notes/blob/main/distcc.md

谢谢!正在配置distcc
